version: "3.7"
services:
  pg-docker:
    image: postgres:16-alpine
    container_name: dev-postgresql
    environment:
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data