version: "3.7"
services:
  db:
    image: postgres:16-alpine
    container_name: dev-postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: catalogoproduto
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
  api:
    image: catalogoproduto
    container_name: dev-api
    ports:
      - "8080:8080"
    depends_on:
      - db
